### ISSUE TITLE
Can't build on Centos7 with readline 6.2

### ISSUE THREAD

**Issue by jbrunski** [rgburke/grv#8]
Build fails with this error:
```
go build --tags static -o grv ./cmd/grv
# github.com/rgburke/grv/cmd/grv
cmd/grv/readline.go: In function 'grv_init_readline':
cmd/grv/readline.go:18:2: error: 'rl_change_environment' undeclared (first use in this function)
 // rl_change_environment = 0;
  ^
cmd/grv/readline.go:18:2: note: each undeclared identifier is reported only once for each function it appears in
make: *** [grv] Error 2
```
I suspect the rl_change_environment variable got introduced in a later version of readline?

On my machine removing line 18 from cmd/grv/readline.go allows it to compile and run.
Not sure what negative effects this change might have...

```
[root@localhost readline-devel-6.2]# uname -a
Linux localhost.localdomain 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost readline-devel-6.2]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@localhost readline-devel-6.2]# go version
go version go1.9.1 linux/amd64
```

**Comment by rgburke** [comment]
Thanks for reporting this issue. The `rl_change_environment` variable is only available in readline versions 6.3 and later. This variable stops readline from setting environment variables when a SIGWINCH is received.

With this variable removed the display of GRV gets a bit messed up when the terminal is resized and a prompt is open (when entering a search term, setting a config variable, etc...). I can't see a clear way to work around this for readline version 6.2, as it looks like the `rl_change_environment` variable was introduced to resolve this.

For the moment it should now be possible to compile GRV successfully with readline 6.2 using the latest master. Hopefully a terminal resize with a prompt is open is a fairly rare occurrence and shouldn't effect normal usage.

**Comment by jbrunski** [comment]
Sounds like a good solution to me. Thanks for looking into it.

Out of interest, where did you find the documentation on the `rl_change_environment` variable?
I tried to look into the [readline release notes](https://tiswww.case.edu/php/chet/readline/CHANGES) but didn't any mention of that variable...

**Comment by rgburke** [comment]
I've been using http://tiswww.case.edu/php/chet/readline/readline.html#SEC44 which gives an in depth description of the readline library.
